### ISSUE TITLE
Given answer seems wrong

### ISSUE THREAD

**Issue by sandgate-dev** [learn-co-curriculum/dsc-1-02-10-creating-functions-lab#1]
```
list_of_destinations = ['finland', 'canada', 'croatia']
# next_up() # 'argentina'

```
You are stating 

> the destination with the lowest index

which is 0. And should return in this case 'finland'.

Similarly, so is the next step.

**Comment by calremmel** [comment]
Yes, for the next_up() function, the expected return results for the function are switched. 'finland' and 'argentina' ought to be switched with one another.

**Comment by PeterBell** [comment]
Fixed  with https://github.com/learn-co-curriculum/dsc-1-02-10-creating-functions-lab/commit/fddf5f1f823afeba2291efb542d684c86337f38d - thanks so much Chris!
